### ISSUE TITLE
Move Welcome documents into this repository as separate pages

### ISSUE THREAD

**Issue by nickserv** [paircolumbus/paircolumbus.github.io#1]
See the markdown documents in https://github.com/paircolumbus/Welcome.

**Comment by jaybobo** [comment]
Just noticed this. It's definitely something we should do soon. I may see if one of our new regulars wants to give it a try.

**Comment by nickserv** [comment]
I feel like we could probably move all of Welcome into the site if that's OK with you. We can keep the repository around just to link to the new website pages so people won't get lost in 404s.

**Comment by jaybobo** [comment]
I agree. :100: %
