### ISSUE TITLE
Include a link to GitHub's Markdown guide

### ISSUE THREAD

**Issue by nickserv** [paircolumbus/paircolumbus.github.io#11]
> Might not be a bad idea to also include a link to GitHub's Markdown guide.
> https://guides.github.com/features/mastering-markdown/
> @degoeym

**Comment by jaybobo** [comment]
I think this should go in beginner resources or even in CONTRIBUTING. What's the idea around adding a md guide?

**Comment by nickserv** [comment]
The contents of CONTRIBUTING were moved to the Challenges page. I think that link would fit well in the Resources page. I think it would be cool to have a Markdown challenge similar to our existing challenges, or we can link to http://markdowntutorial.com/.
