### ISSUE TITLE
Remove the old readme

### ISSUE THREAD

**Issue by nickserv** [paircolumbus/paircolumbus.github.io#17]
[OLD_README.txt](https://github.com/paircolumbus/paircolumbus.github.io/blob/master/OLD_README.md) used to be the readme for Welcome. Ideally, I would like to merge the contents of this file into the site and/or the site's readme and then remove it.

**Comment by jaybobo** [comment]
I think what we have so far works.

**Comment by nickserv** [comment]
You're saying we don't need OLD_README.txt anymore? If so, I'll delete it.
