### ISSUE TITLE
Improve map/address display on mobile

### ISSUE THREAD

**Issue by nickserv** [paircolumbus/paircolumbus.github.io#6]
Unfortunately, the Google Maps widget is fairly small on mobile devices. It's difficult to use and also hard to read the address. It would be nice if we could set a breakpoint to replace the widget with the address, or use a map widget that supports mobile better.

**Comment by degoeym** [comment]
Check out the fix I just suggested. Basically I'm using Bootstrap's hidden-\* classes to hide the embed on mobile devices, replacing it with a URL the user can click to get to a Google Maps shortened URL for the address, which I think will open it on their phone. Feel free to correct me if I'm wrong.

**Comment by degoeym** [comment]
@nicolasmccurdy or @jaybobo

**Comment by nickserv** [comment]
I like your idea, though I'm against including Bootstrap just for those helper classes (I'm assuming you included it just for the example).

**Comment by degoeym** [comment]
Maybe I fatfingered the copy/paste, because when I added it to the header I also noticed it lower in the project and thought Bobo had already included it, thus I thought it was already part of the project.

**Comment by nickserv** [comment]
By the way, I have another Bootstrap-related idea. I just recently remember that Bootstrap has support for responsive embeds, and it turns out that embeds from Google Maps are much more readable on mobile devices if you use responsive embeds. [Here's an example.](http://codepen.io/nicolasmccurdy/full/RNOPdp/) Interestingly enough, it seems like the Google Maps embed is actually responsive, you just have to set the right CSS on its container.

**Comment by degoeym** [comment]
Looks like that could work, but when testing responsive design I also toy with adjusting the size of my browser window, and the point of interest on the map gets gobbled up when you do that. The concern is that tablet users going from portrait to landscape mode might have issues with the map.

**Comment by nickserv** [comment]
I opened this in Chrome's device model use the iPad 3/4 viewport size, and switching orientation didn't seem to be an issue. The point goes from being in the dead center to be a little closer to the bottom right corner, but it's still fully visible.

**Comment by degoeym** [comment]
Just added a feature branch (though it just hit me that I need to remove the Bootstrap refference) to implement the fix you suggested. I'd say it looks good to me if it looks good to you.

**Comment by degoeym** [comment]
Yeeeeeeeah, you'd think the guy who wrote the Bootstrap challenge would not have done what I just did, but I corrected my mistake. I also placed the CDN refference before the main CSS for the site so all of the core styling will still be there.

**Comment by nickserv** [comment]
Please add this to your `<head>`:

``` html
<meta name="viewport" content="width=device-width">
```

That should fix mobile devices. I also noticed some weird stalling and performance issues when viewing in Chrome's device mode with an iPhone 6 viewport, but I think it's just an issue with the developer tools.

**Comment by degoeym** [comment]
Added to my feature branch. If everything looks good I'll merge it with my main branch, push up, and you can merge the request if you want.

**Comment by nickserv** [comment]
On second thought, I think it would be useful to move your feature branch to this repository (as a feature branch still) and I can add you as a collaborator so we can both work on it. I'd like to remove the dependency on Bootstrap before we merge if possible, then I'll make a pull request or directly merge into master.

**Comment by degoeym** [comment]
Could likely pull out the CSS for these markups from Bootstrap's CSS itself, or I can pare down Bootstrap to only include the relevant items for these classes to make it smaller. Unless you're talking about just not even using Bootstrap at all.

**Comment by nickserv** [comment]
I've had luck with copying small snippets from Bootstrap in the past. It seems like these classes are all defined in [responsive-embed.less](https://github.com/twbs/bootstrap/blob/master/less/responsive-embed.less). We could compile this to CSS or SCSS and include it as a file in the site for now, and we can remove the styles we don't need as we go on.

**Comment by nickserv** [comment]
For an issue, this conversation is getting very implementation-specific. Is it OK if I move your branch to this repository, give you push access, and create a pull request which we can use for the rest of this discussion?

**Comment by degoeym** [comment]
I might also be able to write this with a bit of jQuery to change the iframe's width when the viewport width is changed, unless you also don't want to include jQuery. Could look to do it with straight up JS I suppose.

**Comment by degoeym** [comment]
Sure, feel free to move it if that's what you want.

**Comment by nickserv** [comment]
Good point, though I would rather solve this with CSS if possible.

**Comment by degoeym** [comment]
Then either paring down the Bootstrap CSS to only include what we need, or pulling out the CSS we need from Bootstrap and including it in the site CSS, is likely the best way to go. I'm guessing you don't want Bootstrap because you don't want to load the full framework for a handful of attributes?

**Comment by nickserv** [comment]
@degoeym We decided to stick with a text link for the address to make the mobile site simpler. Thanks for your contributions though!
